mysite2/config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("medicine.urls")),
]

mysite2/medicine/urls.py
from django.urls import path
from . import views

app_name    = "medicine"
urlpatterns = [
    path('', views.index, name="index"),
    path('search/', views.search, name="search"),
    path('single/<uuid:pk>/', views.single, name="single"),

]

mysite2/medicine/models.py
from django.db import models
from django.utils import timezone

import uuid

class Medicine(models.Model):

    class Meta:
        db_table = "medicine"

    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    name        = models.CharField(verbose_name="医薬品名",max_length=100)
    dt          = models.DateTimeField(verbose_name="登録日",default=timezone.now)
    effect      = models.TextField(verbose_name="作用と効果",blank=True)
    caution     = models.TextField(verbose_name="使用上の注意",blank=True)
    dosage      = models.TextField(verbose_name="用法・用量",blank=True)
    side_effect = models.TextField(verbose_name="副作用",blank=True)

    def __str__(self):
        return self.name

mysite2/medicine/views.py
from django.shortcuts import render,redirect
from django.views import View

#クエリビルダ(複雑な検索処理を行う事ができる)
from django.db.models import Q

#JavaScript用にJSONレスポンスを返す
from django.http.response import JsonResponse

#レンダリングした後、文字列型にして返す
from django.template.loader import render_to_string


from .models import Medicine


#正規表現を使うので、インポート
import re

class IndexView(View):

    def get(self, request, *args, **kwargs):

        #何も書かれていない医薬品の炙り出し。
        medicines   = Medicine.objects.filter(effect="",caution="",dosage="",side_effect="")
        print(len(list(medicines.values())))

        #医薬品の開発会社が違うだけで中身は同じ(「」で囲まれた部分を除外し、比較。一致しているものを表示もしくは削除する。)
        medicines   = Medicine.objects.all().exclude(effect="",caution="",dosage="",side_effect="").order_by("name")

        duplicate   = 0
        old_name    = ""
        for medicine in medicines:
            new_name    = medicine.name

            #print("変更前:" + new_name)
            #print("変更後:" + re.sub("「.*」","",new_name))

            new_name    = re.sub("「.*」","",new_name)

            if old_name == new_name:
                #print("重複している")
                #TODO:ここで重複したmedicineのIDを記録する。
                duplicate += 1

            old_name    = new_name

        print("重複している数" + str(duplicate))

        #約22200行 → 重複と説明なしの医薬品除外 → 約9400行
        #Herokuの運用も可能になる。

        return render(request,"medicine/index.html")

index   = IndexView.as_view()


#Jsonでレスポンスを返す。
class SearchView(View):

    def get(self, request, *args, **kwargs):

        json    = {"error":True}

        if "search" in request.GET:

            #(1)キーワードが空欄もしくはスペースのみの場合、ページにリダイレクト
            if request.GET["search"] == "" or request.GET["search"].isspace():

                #リダイレクトではなくAjaxで送信されているのでjsonで返す。
                #return redirect("medicine:index")
                return JsonResponse(json)

            #チェックボックスがいずれも押されていない場合検索しない(全件出力され、処理が遅くなる)
            if "name" not in request.GET and "effect" not in request.GET and "caution" not in request.GET and "dosage" not in request.GET and "side_effect" not in request.GET:

                #リダイレクトではなくAjaxで送信されているのでjsonで返す。
                #return redirect("medicine:index")
                return JsonResponse(json)


            #(2)キーワードをリスト化させる(複数指定の場合に対応させるため)
            search      = request.GET["search"].replace("　"," ")
            search_list = search.split(" ")

            #(3)クエリを作る
            query       = Q()
            for word in search_list:
                if word == "":
                    continue

                #TIPS:AND検索の場合は&を、OR検索の場合は|を使用する。
                if "name"        in request.GET:
                    query |= Q(name__contains=word)

                if "effect"      in request.GET:
                    query |= Q(effect__contains=word)

                if "caution"     in request.GET:
                    query |= Q(caution__contains=word)

                if "dosage"      in request.GET:
                    query |= Q(dosage__contains=word)

                if "side_effect" in request.GET:
                    query |= Q(side_effect__contains=word)

            #(4)作ったクエリを実行
            medicines   = Medicine.objects.filter(query)
        else:
            medicines   = []

        context = { "medicines":medicines }

        #検索結果のレンダリングを文字列型にして返す。
        content = render_to_string("medicine/search.html",context,request)

        #エラーフラグをFalseにして、検索結果のHTML(文字列型)のデータをJSON形式でレスポンス、JSに引き渡す。
        json["error"]   = False
        json["content"] = content

        return JsonResponse(json)


search  = SearchView.as_view()
    

#テーブルにスタックする時、医薬品単体のデータを返す。
class SingleView(View):

    def get(self, request, pk, *args, **kwargs):
        print("single")
        json    = { "error":True }

        #pkから医薬品情報一件を抜き取る、JSONで返すので辞書型に書き換え。
        medicine    = Medicine.objects.filter(id=pk).first()

        #医薬品情報が無い場合はエラーを返す。
        if not medicine:
            return JsonResponse(json)

        
        #json形式で送信できるように辞書型に変換する
        dic = {}
        dic["name"]         = medicine.name
        dic["effect"]       = medicine.effect     
        dic["caution"]      = medicine.caution    
        dic["dosage"]       = medicine.dosage     
        dic["side_effect"]  = medicine.side_effect


        json["error"]       = False
        json["medicine"]    = dic

        return JsonResponse(json)


single  = SingleView.as_view()

mysite2/templates/medicine/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>医薬品情報</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script src="{% static 'medicine/js/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'medicine/css/style.css' %}">

</head>
<body>

    <header class="bg-primary">
        <a class="text-white" href="{% url 'medicine:index' %}"><h1>医薬品情報</h1></a>
    </header>

    
    <!--ここにSearchViewのパスを-->
    <form id="search_form" action="{% url 'medicine:search' %}" method="GET">

        <!--Ajaxを使った検索をするので、画面遷移は起こらない。検索したときのチェックと検索ワードは残るため、以下のrequest.GET.XXX を全て削除
            デフォルトで医薬品名で検索をするので、checked属性を指定しておく。
        -->
        <input id="name"        class="chkbox" type="checkbox" name="name"        checked><label class="chk_label" for="name">医薬品名    </label>
        <input id="effect"      class="chkbox" type="checkbox" name="effect"      ><label class="chk_label" for="effect"     >作用と効果  </label>
        <input id="caution"     class="chkbox" type="checkbox" name="caution"     ><label class="chk_label" for="caution"    >使用上の注意</label>
        <input id="dosage"      class="chkbox" type="checkbox" name="dosage"      ><label class="chk_label" for="dosage"     >用法・用量  </label>
        <input id="side_effect" class="chkbox" type="checkbox" name="side_effect" ><label class="chk_label" for="side_effect">副作用      </label>

        <input id="search_text" type="text" name="search" placeholder="医薬品名" value="">
        <input id="search_button" class="btn btn-primary" type="button" value="検索">
    </form>

    <ul id="search_result" class="search_result">
    </ul>

    <table class="table">
        <thead class="thead-dark"> 
            <tr id="table_name">
                <th>比較項目/薬品名</th>
            </tr>
        </thead>
        <tbody>
            <tr id="table_effect"     ><td>作用と効果  </td></tr>
            <tr id="table_caution"    ><td>使用上の注意</td></tr>
            <tr id="table_dosage"     ><td>用法・用量  </td></tr>
            <tr id="table_side_effect"><td>副作用      </td></tr>
        </tbody>
    </table>


</body>
</html>

mysite2/templates/medicine/search.html
{% for medicine in medicines %}
<li>{{ medicine.name }} {{ medicine.effect|truncatechars_html:50 }} <button class="btn btn-outline-success stack" value="{{ medicine.id }}">スタック</button></li>
{% endfor %}